---
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: タイムゾーンを設定
  timezone:
    name: "{{ timezone }}"

- name: NTPサーバーを設定
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^NTP='
    line: "NTP={{ ntp_server }}"
    create: yes
  notify: restart systemd-timesyncd

- name: NTPを有効化
  systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started
