---
- name: Proxmox Host Setup
  hosts: all
  become: true
  # define in terraform variables
  # vars:
  #   network:
  #     uplink_interface:
  #     mgmt:
  #       address:
  #       gateway:
  #     vlan10:
  #       address:
  #       gateway:
  #     vlan20:
  #       address:
  #       gateway:
  #     vlan30:
  #       address:
  #       gateway:
  #   ntp_servers:
  #     - ntp.nict.jp
  #     - ntp.jst.mfeed.ad.jp
  roles:
    - install_pkg
    - networking
    - time_sync
  