---
- name: Setup Proxmox Master Node
  hosts: all
  become: true
  # define in terraform variables
  # vars:
  #   role: "master"
  #   cluster_name: "{{ cluster_name }}"
  #   ceph_devices:
  #   ceph_network: "10.0.0.0/24"

  roles:
    - cluster_setup_master
    - proxmox-storage-config
    # - storage_setup
  