---
- name: Setup Proxmox Slave Node
  hosts: all
  become: true
  vars:
  # define in terraform variables
  # vars:
  #   role: "slave"
  #   cluster_name: "{{ cluster_name }}"
  #   ceph_devices:
  #   ceph_network: "10.0.0.0/24"

  roles:
    - cluster_setup
    # - storage_setup
  