---
- name: Show passed variables
  debug:
    msg: "uplink_interface={{ uplink_interface }}, ovs_ip_address={{ ovs_ip_address }}, ovs_gateway={{ ovs_gateway }}"

- name: Configure network interfaces
  template:
    src: templates/interfaces.j2
    dest: /etc/network/interfaces
    mode: '0644'
    backup: yes
  notify: restart networking
