---
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

# apt install net-tools

- name: Install Ceph packages (Proxmox)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - ceph
    - ceph-common
    - ceph-mgr
    - ceph-mon
    - ceph-osd
    - ceph-fuse

- name: install openvswitch-switch
  apt:
    name: openvswitch-switch
    state: present

- name: Open vSwitch status check
  systemd:
    name: openvswitch-switch
    enabled: yes
    state: started

- name: Clean up apt cache
  apt:
    autoclean: yes
    autoremove: yes
