--- 
- name: Check if user already exists
  command: "pveum user list --output-format json"
  register: existing_users
  changed_when: false

- name: Parse existing user list
  set_fact:
    user_exists: "{{ proxmox_user in (existing_users.stdout | from_json | map(attribute='userid') | list) }}"

- name: Ensure user exists
  command: "pveum user add {{ proxmox_user }}"
  when: not user_exists
  register: user_add_result
  failed_when: false
  changed_when: true

- name: Create API token with JSON output
  shell: "pveum user token add {{ proxmox_user }} {{ token_id }} --output-format json"
  when: not user_exists
  register: token_create
  changed_when: "'value' in token_create.stdout"
  failed_when: false

- name: Debug token output
  when: not user_exists
  debug:
    var: token_create.stdout

- name: Write token to remote tmp
  when: not user_exists
  copy:
    content: "{{ token_create.stdout }}"
    dest: "/tmp/proxmox_token.json"
    mode: '0600'

# - name: Grant Administrator role to token
#   when: not user_exists
#   command: "pveum acl modify / -token '{{ proxmox_user }}!{{ token_id }}' -role Administrator"

- name: Grant Administrator role to token
  when: not user_exists
  command: "pveum group add iac -comment 'Admin group'"

- name: Grant Administrator role to token
  when: not user_exists
  command: "pveum acl modify / -group iac -role Administrator"

- name: Grant Administrator role to token
  when: not user_exists
  command: "pveum user modify {{ proxmox_user }} -group iac"

- name: Fetch token to control machine
  when: not user_exists
  fetch:
    src: "/tmp/proxmox_token.json"
    dest: "{{ output_path }}"
    flat: yes
  notify: cleanup token tmp file
